/* generated by unplugin-react-components */
export {}
declare global{
	const CbesRouter: typeof import('./src/controllers/cbes')['default']
	const HomeRouter: typeof import('./src/controllers/homeRouter')['default']
	const Navbar: typeof import('./src/components/layout/navbar')['default']
}